name: Deploy to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (SSR + prerender)
        run: npm run build

      - name: Prepare static site for Pages
        run: |
          set -euo pipefail
          mkdir -p out
          cp -R dist/acf-angular/browser/* out/
          # Set base href for project pages (https://<user>.github.io/<repo>/)
          find out -name "*.html" -print0 | xargs -0 -I{} sed -i 's#<base href="/">#<base href="/acf-angular/">#g' {}
          # Fix absolute image paths so they work under /acf-angular
          find out -name "*.html" -print0 | xargs -0 -I{} sed -i 's#\(["'"'"'"'"']\)/images/#\1/acf-angular/images/#g' {}
          find out -name "*.css" -print0 | xargs -0 -I{} sed -i 's#url(/images/#url(/acf-angular/images/#g' {}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
